# Generated by Django 3.0.7 on 2020-06-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_s_server', '0002_auto_20200616_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
